### ISSUE TITLE
Enable Travis-CI build

### ISSUE THREAD

**Issue by SSaishruthi** [IBM/MAX-Question-Answering-Web-App#14]
Travis has not been configured for this repository. Once it is we need to reflect the build status in https://github.com/CODAIT/max-central-repo/blob/master/max-model-status.md

**Comment by yil532** [comment]
please see this PR https://github.com/IBM/MAX-Question-Answering-Web-App/pull/17 for Travis CI build

**Comment by ptitzler** [comment]
Initially this test will only verify that flake8 passes

**Comment by yil532** [comment]
Merged PR and created build badge as well.

**Comment by ptitzler** [comment]
Closed by #17
