### ISSUE TITLE
App badge link is not working

### ISSUE THREAD

**Issue by SSaishruthi** [IBM/MAX-Question-Answering-Web-App#15]
We are using a status badge in https://github.com/CODAIT/max-central-repo/blob/master/max-model-status.md to visualize the current application status for our demo applications. For  MAX-Question-Answering-Web-App the status check `https://img.shields.io/website/http/max-question-answering-web-app.max.us-south.containers.appdomain.cloud.svg` always indicates that the application is down, even if it is running. The root cause is likely that this application does not support HEAD requests:

```
$ curl -I http://max-question-answering-web-app.max.us-south.containers.appdomain.cloud
HTTP/1.1 500 INTERNAL SERVER ERROR
Date: Wed, 08 Apr 2020 19:31:37 GMT
Content-Type: text/html
Connection: keep-alive

```

Once a fix is delivered https://github.com/CODAIT/max-central-repo/blob/master/max-model-status.md needs to be updated.

**Comment by ptitzler** [comment]
Closed by #16
