### ISSUE TITLE
Enhance Travis-CI test to verify that the docker build completes successfully

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Question-Answering-Web-App#19]
This test should be performed after flake8 testing.

**Comment by yil532** [comment]
https://github.com/IBM/MAX-Question-Answering-Web-App/pull/20
Already finished docker build. Please see the PR here.

**Comment by bdwyer2** [comment]
@ptitzler I think that if the docker build fails then everything will fail. I will verify this with a test PR

**Comment by yil532** [comment]
Thank you Brendan @bdwyer2

**Comment by bdwyer2** [comment]
@ptitzler does PR #21 satisfy you or do you want further testing?

**Comment by ptitzler** [comment]
In #20 this line 
```
- docker run -it -d -p 5000:5000 max-question-answering-web-app
```
is incorrect because port 5000 is not exposed:

https://github.com/IBM/MAX-Question-Answering-Web-App/blob/master/Dockerfile#L23

In general I believe it would have been better to run the docker build after flake 8 (in the scripts section). The motivation is that the source code must be syntactically error free before one would attempt to package it. But I guess one that doesn't change the outcome materially.

**Comment by bdwyer2** [comment]
We can change add `docker ps | grep max-question-answering-web-app` to the script section and move `flake8` to the build section

**Comment by yil532** [comment]
Create another PR based on Patrick and Brendan's comments. Thank you for helping me!
https://github.com/IBM/MAX-Question-Answering-Web-App/pull/22
