### ISSUE TITLE
model api deployment ?

### ISSUE THREAD

**Issue by MLnick** [IBM/MAX-Question-Answering-Web-App#2]
In https://github.com/IBM/MAX-Question-Answering-Web-App#deploy-the-model

it says `docker run -it -p 5000:5000 codait/max-question-answering-web-app`, should it not be `docker run -it -p 5000:5000 codait/max-question-answering`?

**Comment by kmh4321** [comment]
That is a typo. On the same note, should we be hosting the web app in a long running instance too?

**Comment by kmh4321** [comment]
Webapp long running instance here: http://max-question-answering-web-app.max.us-south.containers.appdomain.cloud/
