### ISSUE TITLE
Error response from daemon: pull access denied for codait/max-question-answering-web-app

### ISSUE THREAD

**Issue by ghost** [IBM/MAX-Question-Answering-Web-App#3]
I tried running _docker run -it -p 5000:5000 codait/max-question-answering-web-app_ as specified in the README.md file, and the response was: "Error response from daemon: pull access denied for codait/max-question-answering-web-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"

I then run _docker login_, and went to Docker Hub to sign in as well. Both logins were successful, by the way. However, the issue persists. Please how do I work around this?

**Comment by ptitzler** [comment]
Looks like the Docker image wasn't published @kmh4321

**Comment by kmh4321** [comment]
Fixed the readme @pentangeli-ai.

**Comment by splovyt** [comment]
We have published a more up to date version of the web app as well @pentangeli-ai. 

The `docker run -it -p 5000:5000 codait/max-question-answering-web-app` command should work properly now and will provide you with the latest version.

**Comment by ptitzler** [comment]
https://hub.docker.com/r/codait/max-question-answering-web-app
